# Generated by Django 3.1.7 on 2021-03-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=60, null=True)),
                ("order_purchase_date", models.DateField(null=True)),
                ("order_amount", models.FloatField(blank=True, null=True)),
                ("order_items", models.PositiveIntegerField(blank=True, null=True)),
                ("marketplace", models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
